name: lep7.4-push-to-docker-hub

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push container image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push 7.4
        uses: docker/build-push-action@v2
        with:
          context: ./7.4
          no-cache: true
          push: true
          tags: |
            solucionesgbh/lep:7.4
